version: '3.8'

services:
  postgresql:
    image: postgres:15
    container_name: postgresql
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ../data/postgresql:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - .env
    ports:
      - "5050:80"
    volumes:
      - ../data/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgresql