name: test-web-server
services:
  backend:
    image: nginx
    container_name: backend-service
    ports:
      - "8080:80"
    networks:
      ssnd:
  frontend:
    build:
        context: .
        dockerfile: Dockerfile
    image: myphpimage
    container_name: frontend-service
    ports:
      - "8081:80"
    networks:
      ssnd:
        - ipv4_address: 172.18.0.3
networks:
    ssnd:
        external: true
