name: ssnd-web-programovanie

services:
  ssnd-db:
    image: postgres:15
    container_name: ssnd-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ../data/postgresql:/var/lib/postgresql/data
    networks:
        - backend
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5050:80"
    volumes:
      - ../data/pgadmin:/var/lib/pgadmin
    networks:
        - backend
    depends_on:
      - ssnd-db
  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: php-development:8.2
    container_name: php-backend
    restart: unless-stopped
    ports:
      - "8020:80"
    env_file:
      .env
    volumes:
      - ../L20:/var/www/
    depends_on:
      - ssnd-db
    networks:
        - backend
networks:
    backend:
        external: true
        name: ssnd-dev-network