server {
  listen 80;
  server_name app.local;

  # (voliteľné) ochrana pred príliš veľkým telom pri POST upload
  client_max_body_size 10m;

  # /api -> backend:8080
  location /api/ {
    proxy_pass http://172.18.0.5:8080;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
  }

  # /auth -> authentication:8080
#  location /auth/ {
#    proxy_pass http://authentication:8080/;
#    proxy_http_version 1.1;
#    proxy_set_header Connection "";
#  }

  # / -> frontend:8080
  location / {
    proxy_pass http://172.18.0.4:8080/;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
  }
}
